# Generated by Django 6.0 on 2026-04-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="api.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
